[theme]
primaryColor = "#5E6AD2"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F4F4F5"
textColor = "#18181B"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
